--- 
output: html_document
---
<style type="text/css">
  body{
  font-size: 8pt;
}
</style>

```{r, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r code, include=FALSE}

library(sf)
library(leaflet.extras)
library(leaflet.providers)
library(dplyr)
library(htmltools)
getwd()
Zones <-st_read("Zones/Zones.shp")
labels <- c("Subalpine", "Alpine", "High Alpine")
bins <- c(1,2,3)
#pal <- colorFactor(c("red", "green", "blue"), 1:3)
col<-c("green", "yellow" , "#7E1900")
pal <- colorNumeric(c('green', 'yellow' , '#7E1900'), domain=Zones$value)


m <- leaflet()

#m <- addLayersControl(m, 
 #                     baseGroups = c("OSM (topographic)"),
  #                    overlayGroups = c("Polyline", "Line"),
   #                   options = layersControlOptions(collapsed = TRUE))
m <-addProviderTiles(m, "Esri.WorldTopoMap") %>% addPolygons(data=Zones, fillColor = ~pal(Zones$value), smoothFactor = 0, weight = 2, opacity = 1, color = "NA", fillOpacity = 0.4) %>%
  addLegend("bottomright", colors = c('green', 'yellow', '#7E1900'), values = ~values,
            title = "სიმაღლებრივი სარტყელი / Elevation Zones",
            labels = c(" სუბალპური / Subalpine (1277 - 2000 m)", "ალპური / Alpine (2000 - 2600 m)", " მაღალი ალპური / High Alpine (2600 - 3360 m)"),
            opacity = 1
  )




```


```{r map, width = 40, height = 30, echo=FALSE}
browsable(
  tagList(
    list(
      tags$head(
        tags$style(
              ".leaflet .legend i{
          width: 4px;
          height: 4px;
              }"
            )
        ),
      m)))

```

