--- 
output: html_document
---

```{r, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


 
 
```{r code, include=FALSE}

library(sf)
library(leaflet.extras)
library(leaflet.providers)
library(dplyr)

library(sf) 
library(dplyr)


getwd()
Zones <-st_read("Zones/Zones.shp")
labels <- c("Subalpine", "Alpine", "High Alpine")
bins <- c(1,2,3)
#pal <- colorFactor(c("red", "green", "blue"), 1:3)

Zones <-st_read("Zones/Zones.shp")
#pal <- colorNumeric(c('yellow', 'orange' , 'orange'), domain=Zones$value)
pal <- colorNumeric(c('orange', 'orange' , 'orange'), domain=Zones$value)
m <- leaflet()
m <-addProviderTiles(m, "Esri.WorldTopoMap") %>% addPolygons(data=Zones, fillColor = ~pal(Zones$value), smoothFactor = 0, weight = 1, opacity = 1, color = "NA", fillOpacity = 0.5) %>%
  addLegend("bottomright", colors = c('orange', 'orange', 'orange'), values= ~values,
            title = "ზვავსაშიშროების საფეხური / Avalanche Hazard Level",
            labels = c("3  - მნიშვნელოვანი / Considerable", "3  - მნიშვნელოვანი / Considerable", "3  - მნიშვნელოვანი / Considerable"),
            opacity = 1
  ) 
```
```{r map, width = 40, height = 30, echo=FALSE}
m
```


